# This workflow will build a project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run all tests
      run: ./gradlew test --stacktrace
    - name: Send job dispatch to update front-end submodule
      if: ${{ github.event_name == 'push' }}
      run: |
        curl -X POST https://api.github.com/repos/Mexolius/IO/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u Mexolius:${{ secrets.ACCESS_TOKEN }} \
        --data '{"event_type": "update_module"}'
